export function getFriendsCopy(locale: string) {
  if (locale === "fr") {
    return {
      title: "Amis",
      description:
        "Gérez vos demandes et voyez les activités récentes de vos amis.",
      entryTitle: "Amis",
      entryDescription: "Demandes, amis et activités",
      openFriends: "Voir les amis",
      addTitle: "Ajouter un ami",
      addDescription: "Code ami ou pseudo.",
      close: "Fermer",
      ownFriendCode: "Votre code ami",
      friendCodeLabel: "Code ami",
      copyOwnFriendCode: "Copier mon code ami",
      ownFriendCodeCopied: "Copié",
      showMyQr: "Afficher mon QR code",
      myQrAction: "QR",
      myQrTitle: "Mon QR ami",
      myQrDescription:
        "Montrez ce QR code à un ami pour qu'il confirme votre profil.",
      myQrFallback: "Le code ami reste disponible en cas d'échec du scan.",
      qrGenerateFailed: "Impossible de générer le QR code.",
      scanQrAdd: "Scanner un QR ami",
      scanQrHint: "Le scan remplira le code ami sans envoyer la demande.",
      scanQrEyebrow: "Ajout rapide",
      scanQrTitle: "Scanner le QR ami",
      scanQrDescription:
        "Placez le QR code dans le cadre. Vous confirmerez avant l'envoi.",
      scanQrDetected: "QR détecté",
      scanQrManualFallback: "Vous pouvez saisir le code ami manuellement.",
      manualInput: "Saisie manuelle",
      cameraUnsupported:
        "Ce navigateur ne permet pas d'ouvrir la caméra. Utilisez le code ami.",
      cameraPermissionDenied:
        "La caméra est indisponible ou refusée. Utilisez le code ami.",
      invalidQrCode:
        "Ce QR code ne correspond pas à un code ami Next Fun.",
      searchLabel: "Code ami ou pseudo",
      searchPlaceholder: "ex. 123456",
      searchHint: "Le code ami est le plus fiable.",
      previewLoading: "Recherche...",
      previewTitle: "Confirmer l'ami",
      previewReady: "Demande possible",
      previewBlocked: "Impossible",
      previewAvailable: "Vérifiez le profil avant d'envoyer.",
      previewSelf: "C'est votre propre code ami.",
      previewFriends: "Déjà ami.",
      previewPending: "Demande déjà envoyée.",
      previewNotFound: "Aucun ami trouvé avec ce code.",
      previewAmbiguous: "Plusieurs personnes correspondent. Utilisez le code ami.",
      previewError: "Aperçu indisponible. Réessayez.",
      sentSuccess: "Demande envoyée.",
      sendingTo: (name: string) => `Envoi à ${name}...`,
      messageLabel: "Message",
      messagePlaceholder: "Message optionnel",
      send: "Envoyer",
      sending: "Envoi...",
      friendsTitle: "Liste d'amis",
      friendsDescription: (count: number) =>
        `${count} ami${count > 1 ? "s" : ""} · voyez leurs sorties récentes.`,
      friendsListDescription: "Voyez les sorties récentes de vos amis.",
      friendActivitySummary: (date: string, title: string, state = "UPCOMING") =>
        state === "ONGOING"
          ? `En cours : « ${title} »`
          : state === "ENDED"
            ? `A rejoint « ${title} » le ${date}`
            : `Prévoit « ${title} » le ${date}`,
      moreActivities: (count: number) => `+${count}`,
      showMoreActivitiesLabel: (count: number) =>
        `Voir ${count} activité${count > 1 ? "s" : ""} en plus`,
      collapseActivities: "Réduire",
      friendsEmptyTitle: "Aucun ami pour le moment",
      friendsEmptyDescription: "Ajoutez un ami pour démarrer.",
      incomingTitle: "Demandes reçues",
      incomingDescription: "Vérifiez l'identité avant d'accepter.",
      incomingEmpty: "Aucune demande reçue.",
      outgoingTitle: "Demandes envoyées",
      outgoingEmpty: "Aucune demande en attente.",
      accept: "Accepter",
      reject: "Refuser",
      cancel: "Annuler",
      remove: "Supprimer",
      message: "Message",
      removeConfirm: "Supprimer cet ami ?",
      acting: "Traitement...",
      noBio: "Aucune bio.",
      requestedAt: (date: string) => `Envoyée le ${date}`,
      invalidRequest: "Requête invalide. Réessayez plus tard.",
      authError: "Connectez-vous pour gérer vos amis.",
      cannotAddSelf: "Vous ne pouvez pas vous ajouter vous-même.",
      targetNotFound: "Aucun utilisateur actif trouvé avec cette valeur.",
      ambiguousTarget:
        "Plusieurs utilisateurs correspondent. Utilisez le code ami exact.",
      alreadyFriends: "Vous êtes déjà amis.",
      pendingExists: "Une demande est déjà en attente entre vous.",
      requestUnavailable: "Cette demande n'est plus disponible.",
      friendshipUnavailable: "Cette relation d'amitié n'existe plus.",
      failed: "Action impossible pour le moment. Réessayez plus tard.",
    };
  }

  if (locale === "en") {
    return {
      title: "Friends",
      description: "Add friends and see what they are joining.",
      entryTitle: "Friends",
      entryDescription: "Requests, friends, and activities",
      openFriends: "Open friends",
      addTitle: "Add a friend",
      addDescription: "Friend code or nickname.",
      close: "Close",
      ownFriendCode: "Your friend code",
      friendCodeLabel: "Friend code",
      copyOwnFriendCode: "Copy my friend code",
      ownFriendCodeCopied: "Copied",
      showMyQr: "Show my QR code",
      myQrAction: "QR",
      myQrTitle: "My friend QR",
      myQrDescription:
        "Show this QR code so a friend can confirm your profile.",
      myQrFallback: "Use the friend code if scanning fails.",
      qrGenerateFailed: "Could not generate the QR code.",
      scanQrAdd: "Scan friend QR",
      scanQrHint: "Scanning fills the friend code. It will not send automatically.",
      scanQrEyebrow: "Quick add",
      scanQrTitle: "Scan friend QR",
      scanQrDescription:
        "Place the QR code in the frame. You will confirm before sending.",
      scanQrDetected: "QR found",
      scanQrManualFallback: "You can still enter the friend code manually.",
      manualInput: "Enter manually",
      cameraUnsupported:
        "This browser cannot open the camera. Use the friend code instead.",
      cameraPermissionDenied:
        "Camera permission was denied or unavailable. Use the friend code.",
      invalidQrCode:
        "This QR code is not a valid Next Fun friend code.",
      searchLabel: "Friend code or nickname",
      searchPlaceholder: "e.g. 123456",
      searchHint: "Friend code is the most accurate.",
      previewLoading: "Searching...",
      previewTitle: "Confirm friend",
      previewReady: "Can send",
      previewBlocked: "Cannot send",
      previewAvailable: "Check the profile before sending.",
      previewSelf: "This is your own friend code.",
      previewFriends: "Already friends.",
      previewPending: "Request already sent.",
      previewNotFound: "No friend found with this code.",
      previewAmbiguous: "Multiple people matched. Use the exact friend code.",
      previewError: "Preview unavailable. Try again.",
      sentSuccess: "Request sent.",
      sendingTo: (name: string) => `Sending to ${name}...`,
      messageLabel: "Message",
      messagePlaceholder: "Optional message",
      send: "Send",
      sending: "Sending...",
      friendsTitle: "Friend list",
      friendsDescription: (count: number) =>
        `${count} friend${count === 1 ? "" : "s"} · see what they are up to.`,
      friendsListDescription: "See your friends' recent plans.",
      friendActivitySummary: (date: string, title: string, state = "UPCOMING") =>
        state === "ONGOING"
          ? `At “${title}” now`
          : state === "ENDED"
            ? `Recently joined “${title}” on ${date}`
            : `Plans to join “${title}” on ${date}`,
      moreActivities: (count: number) => `+${count}`,
      showMoreActivitiesLabel: (count: number) =>
        `Show ${count} more activit${count === 1 ? "y" : "ies"}`,
      collapseActivities: "Collapse",
      friendsEmptyTitle: "No friends yet",
      friendsEmptyDescription: "Add a friend to get started.",
      incomingTitle: "Incoming requests",
      incomingDescription: "Check who it is before accepting.",
      incomingEmpty: "No incoming requests.",
      outgoingTitle: "Sent requests",
      outgoingEmpty: "No pending sent requests.",
      accept: "Accept",
      reject: "Reject",
      cancel: "Cancel",
      remove: "Remove",
      message: "Message",
      removeConfirm: "Remove this friend?",
      acting: "Updating...",
      noBio: "No bio yet.",
      requestedAt: (date: string) => `Sent on ${date}`,
      invalidRequest: "Invalid request. Try again later.",
      authError: "Sign in to manage friends.",
      cannotAddSelf: "You cannot add yourself.",
      targetNotFound: "No active user found with that exact value.",
      ambiguousTarget:
        "Multiple users matched. Use the exact friend code.",
      alreadyFriends: "You are already friends.",
      pendingExists: "A pending request already exists between you.",
      requestUnavailable: "This request is no longer available.",
      friendshipUnavailable: "This friendship no longer exists.",
      failed: "Action failed. Try again later.",
    };
  }

  return {
    title: "好友",
    description: "添加好友，看看大家最近想参加什么。",
    entryTitle: "好友",
    entryDescription: "好友申请、好友列表和近期活动",
    openFriends: "查看好友",
    addTitle: "添加好友",
    addDescription: "输入好友号或昵称。",
    close: "关闭",
    ownFriendCode: "我的好友号",
    friendCodeLabel: "好友号",
    copyOwnFriendCode: "复制我的好友号",
    ownFriendCodeCopied: "已复制",
    showMyQr: "显示我的二维码",
    myQrAction: "二维码",
    myQrTitle: "我的好友二维码",
    myQrDescription: "把这个二维码给朋友扫码，对方确认后再发送好友申请。",
    myQrFallback: "扫码失败时，也可以直接输入上方好友号。",
    qrGenerateFailed: "二维码生成失败，请使用好友号。",
    scanQrAdd: "扫码添加",
    scanQrHint: "扫码只会填入好友号，不会自动发送申请。",
    scanQrEyebrow: "快速添加",
    scanQrTitle: "扫描好友二维码",
    scanQrDescription: "把好友二维码放进框内，识别后会进入确认流程。",
    scanQrDetected: "已识别二维码",
    scanQrManualFallback: "相机不可用时，可手动输入好友号。",
    manualInput: "手动输入",
    cameraUnsupported: "当前浏览器不支持打开相机，请手动输入好友号。",
    cameraPermissionDenied: "相机权限被拒绝或不可用，请手动输入好友号。",
    invalidQrCode: "这个二维码不是有效的 Next Fun 好友二维码。",
    searchLabel: "好友号或昵称",
    searchPlaceholder: "例如：123456",
    searchHint: "好友号最准确。",
    previewLoading: "查找中...",
    previewTitle: "确认好友",
    previewReady: "可发送申请",
    previewBlocked: "不可发送",
    previewAvailable: "发送前请确认对方信息。",
    previewSelf: "这是你自己的好友号。",
    previewFriends: "已经是好友。",
    previewPending: "好友申请已发送。",
    previewNotFound: "没有找到这个好友号。",
    previewAmbiguous: "找到多个同名用户，请使用对方好友号。",
    previewError: "预览暂时不可用，请稍后再试。",
    sentSuccess: "好友申请已发送。",
    sendingTo: (name: string) => `正在发送给 ${name}...`,
    messageLabel: "留言",
    messagePlaceholder: "可选，简单说明你是谁",
    send: "发送申请",
    sending: "发送中...",
    friendsTitle: "好友列表",
    friendsDescription: (count: number) => `${count} 位好友 · 看看大家最近在干什么`,
    friendsListDescription: "看看好友最近在干什么",
    friendActivitySummary: (date: string, title: string, state = "UPCOMING") =>
      state === "ONGOING"
        ? `正在参加「${title}」`
        : state === "ENDED"
          ? `${date}参加过「${title}」`
          : `${date}想去「${title}」`,
    moreActivities: (count: number) => `+${count}`,
    showMoreActivitiesLabel: (count: number) => `查看另外 ${count} 个活动`,
    collapseActivities: "收起",
    friendsEmptyTitle: "还没有好友",
    friendsEmptyDescription: "添加好友后即可开始聊天。",
    incomingTitle: "收到的申请",
    incomingDescription: "确认对方身份后再接受。",
    incomingEmpty: "暂无收到的好友申请。",
    outgoingTitle: "发出的申请",
    outgoingEmpty: "暂无待处理的发出申请。",
    accept: "接受",
    reject: "拒绝",
    cancel: "取消",
    remove: "删除",
    message: "发消息",
    removeConfirm: "确定要删除这位好友吗？",
    acting: "处理中...",
    noBio: "暂无简介。",
    requestedAt: (date: string) => `发送于 ${date}`,
    invalidRequest: "请求无效，请稍后再试。",
    authError: "请登录后管理好友。",
    cannotAddSelf: "不能添加自己为好友。",
    targetNotFound: "没有找到匹配的活跃用户。",
    ambiguousTarget: "找到多个同名用户，请使用对方好友号精确添加。",
    alreadyFriends: "你们已经是好友。",
    pendingExists: "你们之间已经有待处理的好友申请。",
    requestUnavailable: "这条好友申请已不可处理。",
    friendshipUnavailable: "这段好友关系已不存在。",
    failed: "操作失败，请稍后重试。",
  };
}
