export function getFriendsCopy(locale: string) {
  if (locale === "fr") {
    return {
      title: "Amis",
      description:
        "Ajoutez des amis pour voir ensuite les activités où vos proches participent.",
      entryTitle: "Amis",
      entryDescription: "Demandes et liste d'amis",
      openFriends: "Voir les amis",
      addTitle: "Ajouter un ami",
      addDescription:
        "Première version : recherchez une personne par e-mail ou pseudo exact.",
      searchLabel: "E-mail ou pseudo",
      searchPlaceholder: "ex. yiming@example.com",
      searchHint:
        "Si plusieurs personnes ont le même pseudo, utilisez leur e-mail.",
      messageLabel: "Message",
      messagePlaceholder: "Message optionnel",
      send: "Envoyer",
      sending: "Envoi...",
      friendsTitle: "Mes amis",
      friendsDescription: (count: number) =>
        `${count} ami${count > 1 ? "s" : ""} accepte${count > 1 ? "s" : ""}.`,
      friendsEmptyTitle: "Aucun ami pour le moment",
      friendsEmptyDescription:
        "Les amis acceptés apparaîtront ici. Les signaux d'activité viendront ensuite.",
      incomingTitle: "Demandes reçues",
      incomingEmpty: "Aucune demande reçue.",
      outgoingTitle: "Demandes envoyées",
      outgoingEmpty: "Aucune demande en attente.",
      accept: "Accepter",
      reject: "Refuser",
      cancel: "Annuler",
      remove: "Supprimer",
      removeConfirm: "Supprimer cet ami ?",
      acting: "Traitement...",
      noBio: "Aucune bio.",
      requestedAt: (date: string) => `Envoyée le ${date}`,
      invalidRequest: "Requête invalide. Actualisez puis réessayez.",
      authError: "Connectez-vous pour gérer vos amis.",
      cannotAddSelf: "Vous ne pouvez pas vous ajouter vous-même.",
      targetNotFound: "Aucun utilisateur actif trouvé avec cette valeur.",
      ambiguousTarget:
        "Plusieurs utilisateurs correspondent. Utilisez l'e-mail exact.",
      alreadyFriends: "Vous êtes déjà amis.",
      pendingExists: "Une demande est déjà en attente entre vous.",
      requestUnavailable: "Cette demande n'est plus disponible.",
      friendshipUnavailable: "Cette relation d'amitié n'existe plus.",
      failed: "Action impossible pour le moment. Réessayez plus tard.",
    };
  }

  if (locale === "en") {
    return {
      title: "Friends",
      description:
        "Add friends now so activity pages can later show familiar participation signals.",
      entryTitle: "Friends",
      entryDescription: "Requests and accepted friends",
      openFriends: "Open friends",
      addTitle: "Add a friend",
      addDescription: "First version: search by an exact email or nickname.",
      searchLabel: "Email or nickname",
      searchPlaceholder: "e.g. yiming@example.com",
      searchHint: "If a nickname matches multiple people, use their email.",
      messageLabel: "Message",
      messagePlaceholder: "Optional message",
      send: "Send",
      sending: "Sending...",
      friendsTitle: "My friends",
      friendsDescription: (count: number) =>
        `${count} accepted friend${count === 1 ? "" : "s"}.`,
      friendsEmptyTitle: "No friends yet",
      friendsEmptyDescription:
        "Accepted friends will appear here. Activity signals come next.",
      incomingTitle: "Incoming requests",
      incomingEmpty: "No incoming requests.",
      outgoingTitle: "Sent requests",
      outgoingEmpty: "No pending sent requests.",
      accept: "Accept",
      reject: "Reject",
      cancel: "Cancel",
      remove: "Remove",
      removeConfirm: "Remove this friend?",
      acting: "Updating...",
      noBio: "No bio yet.",
      requestedAt: (date: string) => `Sent on ${date}`,
      invalidRequest: "Invalid request. Refresh and try again.",
      authError: "Sign in to manage friends.",
      cannotAddSelf: "You cannot add yourself.",
      targetNotFound: "No active user found with that exact value.",
      ambiguousTarget:
        "Multiple users matched. Use the exact email to add this friend.",
      alreadyFriends: "You are already friends.",
      pendingExists: "A pending request already exists between you.",
      requestUnavailable: "This request is no longer available.",
      friendshipUnavailable: "This friendship no longer exists.",
      failed: "Action failed. Try again later.",
    };
  }

  return {
    title: "好友",
    description: "先建立好友关系，之后活动页会显示熟人报名信号。",
    entryTitle: "好友",
    entryDescription: "好友申请和好友列表",
    openFriends: "查看好友",
    addTitle: "添加好友",
    addDescription: "第一版只支持通过邮箱或昵称精确查找。",
    searchLabel: "邮箱或昵称",
    searchPlaceholder: "例如：yiming@example.com",
    searchHint: "如果昵称重名，请使用对方邮箱添加，避免加错人。",
    messageLabel: "留言",
    messagePlaceholder: "可选，简单说明你是谁",
    send: "发送申请",
    sending: "发送中...",
    friendsTitle: "我的好友",
    friendsDescription: (count: number) => `已接受 ${count} 位好友。`,
    friendsEmptyTitle: "还没有好友",
    friendsEmptyDescription:
      "接受好友申请后会显示在这里，活动熟人信号后续接入。",
    incomingTitle: "收到的申请",
    incomingEmpty: "暂无收到的好友申请。",
    outgoingTitle: "发出的申请",
    outgoingEmpty: "暂无待处理的发出申请。",
    accept: "接受",
    reject: "拒绝",
    cancel: "取消",
    remove: "删除",
    removeConfirm: "确定要删除这位好友吗？",
    acting: "处理中...",
    noBio: "暂无简介。",
    requestedAt: (date: string) => `发送于 ${date}`,
    invalidRequest: "请求无效，请刷新后重试。",
    authError: "请登录后管理好友。",
    cannotAddSelf: "不能添加自己为好友。",
    targetNotFound: "没有找到匹配的活跃用户。",
    ambiguousTarget: "找到多个同名用户，请使用对方邮箱精确添加。",
    alreadyFriends: "你们已经是好友。",
    pendingExists: "你们之间已经有待处理的好友申请。",
    requestUnavailable: "这条好友申请已不可处理。",
    friendshipUnavailable: "这段好友关系已不存在。",
    failed: "操作失败，请稍后重试。",
  };
}
