export function getFriendsCopy(locale: string) {
  if (locale === "fr") {
    return {
      title: "Amis",
      description:
        "Gérez vos demandes et voyez les activités récentes de vos amis.",
      entryTitle: "Amis",
      entryDescription: "Demandes, amis et activités",
      openFriends: "Voir les amis",
      addTitle: "Ajouter un ami",
      addDescription:
        "Saisissez son code ami, son e-mail ou son pseudo.",
      close: "Fermer",
      searchLabel: "Code ami, e-mail ou pseudo",
      searchPlaceholder: "ex. 123456",
      searchHint:
        "Le code ami est le plus fiable. L'e-mail fonctionne aussi.",
      messageLabel: "Message",
      messagePlaceholder: "Message optionnel",
      send: "Envoyer",
      sending: "Envoi...",
      friendsTitle: "Liste d'amis",
      friendsDescription: (count: number) =>
        `${count} ami${count > 1 ? "s" : ""} · voyez leurs sorties récentes.`,
      friendsListDescription: "Voyez ce que vos amis font récemment.",
      friendActivitySummary: (date: string, title: string) =>
        `${date} participe à « ${title} »`,
      moreActivities: (count: number) => `+${count}`,
      showMoreActivitiesLabel: (count: number) =>
        `Voir ${count} activité${count > 1 ? "s" : ""} en plus`,
      collapseActivities: "Réduire",
      friendsEmptyTitle: "Aucun ami pour le moment",
      friendsEmptyDescription: "Vos amis apparaîtront ici.",
      incomingTitle: "Demandes reçues",
      incomingEmpty: "Aucune demande reçue.",
      outgoingTitle: "Demandes envoyées",
      outgoingEmpty: "Aucune demande en attente.",
      accept: "Accepter",
      reject: "Refuser",
      cancel: "Annuler",
      remove: "Supprimer",
      message: "Message",
      removeConfirm: "Supprimer cet ami ?",
      acting: "Traitement...",
      noBio: "Aucune bio.",
      requestedAt: (date: string) => `Envoyée le ${date}`,
      invalidRequest: "Requête invalide. Réessayez plus tard.",
      authError: "Connectez-vous pour gérer vos amis.",
      cannotAddSelf: "Vous ne pouvez pas vous ajouter vous-même.",
      targetNotFound: "Aucun utilisateur actif trouvé avec cette valeur.",
      ambiguousTarget:
        "Plusieurs utilisateurs correspondent. Utilisez l'e-mail exact.",
      alreadyFriends: "Vous êtes déjà amis.",
      pendingExists: "Une demande est déjà en attente entre vous.",
      requestUnavailable: "Cette demande n'est plus disponible.",
      friendshipUnavailable: "Cette relation d'amitié n'existe plus.",
      failed: "Action impossible pour le moment. Réessayez plus tard.",
    };
  }

  if (locale === "en") {
    return {
      title: "Friends",
      description: "Add friends and see what they are joining.",
      entryTitle: "Friends",
      entryDescription: "Requests, friends, and activities",
      openFriends: "Open friends",
      addTitle: "Add a friend",
      addDescription:
        "Enter a friend code, email, or nickname.",
      close: "Close",
      searchLabel: "Friend code, email, or nickname",
      searchPlaceholder: "e.g. 123456",
      searchHint: "Friend code is the most accurate. Email also works.",
      messageLabel: "Message",
      messagePlaceholder: "Optional message",
      send: "Send",
      sending: "Sending...",
      friendsTitle: "Friend list",
      friendsDescription: (count: number) =>
        `${count} friend${count === 1 ? "" : "s"} · see what they are up to.`,
      friendsListDescription: "See what everyone is up to lately.",
      friendActivitySummary: (date: string, title: string) =>
        `${date} joined “${title}”`,
      moreActivities: (count: number) => `+${count}`,
      showMoreActivitiesLabel: (count: number) =>
        `Show ${count} more activit${count === 1 ? "y" : "ies"}`,
      collapseActivities: "Collapse",
      friendsEmptyTitle: "No friends yet",
      friendsEmptyDescription: "Your friends will appear here.",
      incomingTitle: "Incoming requests",
      incomingEmpty: "No incoming requests.",
      outgoingTitle: "Sent requests",
      outgoingEmpty: "No pending sent requests.",
      accept: "Accept",
      reject: "Reject",
      cancel: "Cancel",
      remove: "Remove",
      message: "Message",
      removeConfirm: "Remove this friend?",
      acting: "Updating...",
      noBio: "No bio yet.",
      requestedAt: (date: string) => `Sent on ${date}`,
      invalidRequest: "Invalid request. Try again later.",
      authError: "Sign in to manage friends.",
      cannotAddSelf: "You cannot add yourself.",
      targetNotFound: "No active user found with that exact value.",
      ambiguousTarget:
        "Multiple users matched. Use the exact email to add this friend.",
      alreadyFriends: "You are already friends.",
      pendingExists: "A pending request already exists between you.",
      requestUnavailable: "This request is no longer available.",
      friendshipUnavailable: "This friendship no longer exists.",
      failed: "Action failed. Try again later.",
    };
  }

  return {
    title: "好友",
    description: "添加好友，看看大家最近想参加什么。",
    entryTitle: "好友",
    entryDescription: "好友申请、好友列表和近期活动",
    openFriends: "查看好友",
    addTitle: "添加好友",
    addDescription: "输入好友号、邮箱或昵称，发送好友申请。",
    close: "关闭",
    searchLabel: "好友号、邮箱或昵称",
    searchPlaceholder: "例如：123456",
    searchHint: "好友号最准确，也可以使用邮箱添加。",
    messageLabel: "留言",
    messagePlaceholder: "可选，简单说明你是谁",
    send: "发送申请",
    sending: "发送中...",
    friendsTitle: "好友列表",
    friendsDescription: (count: number) => `${count} 位好友 · 看看大家最近在干什么`,
    friendsListDescription: "看看大家最近在干什么",
    friendActivitySummary: (date: string, title: string) =>
      `${date}参加了「${title}」`,
    moreActivities: (count: number) => `+${count}`,
    showMoreActivitiesLabel: (count: number) => `查看另外 ${count} 个活动`,
    collapseActivities: "收起",
    friendsEmptyTitle: "还没有好友",
    friendsEmptyDescription: "添加好友后会显示在这里。",
    incomingTitle: "收到的申请",
    incomingEmpty: "暂无收到的好友申请。",
    outgoingTitle: "发出的申请",
    outgoingEmpty: "暂无待处理的发出申请。",
    accept: "接受",
    reject: "拒绝",
    cancel: "取消",
    remove: "删除",
    message: "发消息",
    removeConfirm: "确定要删除这位好友吗？",
    acting: "处理中...",
    noBio: "暂无简介。",
    requestedAt: (date: string) => `发送于 ${date}`,
    invalidRequest: "请求无效，请稍后再试。",
    authError: "请登录后管理好友。",
    cannotAddSelf: "不能添加自己为好友。",
    targetNotFound: "没有找到匹配的活跃用户。",
    ambiguousTarget: "找到多个同名用户，请使用对方邮箱精确添加。",
    alreadyFriends: "你们已经是好友。",
    pendingExists: "你们之间已经有待处理的好友申请。",
    requestUnavailable: "这条好友申请已不可处理。",
    friendshipUnavailable: "这段好友关系已不存在。",
    failed: "操作失败，请稍后重试。",
  };
}
